language: python
python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get update
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - conda info -a

install:
  #- sudo apt-get install python-numpy   # needed to get numpy C-headers, which aren't being shown for the travis install
  - conda create --yes -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pip h5py pytest pyproj
  - source activate test-environment
  - pip install . -v

script:
  python -m pytest -v tests/testcases.py

